# Generated by Django 4.1.5 on 2023-01-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTerceraEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='altura',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='handball',
            name='altura',
            field=models.FloatField(max_length=30),
        ),
    ]
